version: '3.9'
services:
  backend:
    image: kb-backend
    ports:
      - "8000:8000"
      - "4001:4001"
    # Add any environment variables, volumes, or other settings as needed
    environment:
      - PORT=8000
      - HOST=localhost
      - WEBSOCKET_PORT=4001
      - FRONTEND_PORT=3000
  frontend:
    image: kb-frontend
    ports:
      - "3000:3000"
    # Add any environment variables, volumes, or other settings as needed
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WEBSOCKET_URL=localhost:4001
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend